//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proyecto_IPC.WSProyecto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosPortBinding", Namespace="http://WS/")]
    public partial class Servicios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback crearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback agregarConocimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getConocimientosDeUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContactosOperationCompleted;
        
        private System.Threading.SendOrPostCallback iniciarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKarmaTotalOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertNumSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback helloOperationCompleted;
        
        private System.Threading.SendOrPostCallback getConocimientosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNumSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTipoUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicios() {
            this.Url = global::Proyecto_IPC.Properties.Settings.Default.Proyecto_IPC_WSProyecto_Servicios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event crearUsuarioCompletedEventHandler crearUsuarioCompleted;
        
        /// <remarks/>
        public event agregarConocimientoCompletedEventHandler agregarConocimientoCompleted;
        
        /// <remarks/>
        public event getConocimientosDeUsuarioCompletedEventHandler getConocimientosDeUsuarioCompleted;
        
        /// <remarks/>
        public event getContactosCompletedEventHandler getContactosCompleted;
        
        /// <remarks/>
        public event iniciarSesionCompletedEventHandler iniciarSesionCompleted;
        
        /// <remarks/>
        public event getKarmaTotalCompletedEventHandler getKarmaTotalCompleted;
        
        /// <remarks/>
        public event insertNumSessionCompletedEventHandler insertNumSessionCompleted;
        
        /// <remarks/>
        public event helloCompletedEventHandler helloCompleted;
        
        /// <remarks/>
        public event getConocimientosCompletedEventHandler getConocimientosCompleted;
        
        /// <remarks/>
        public event getNumSessionCompletedEventHandler getNumSessionCompleted;
        
        /// <remarks/>
        public event getTipoUsuarioCompletedEventHandler getTipoUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crearUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombres, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apellidos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contraseña, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave) {
            object[] results = this.Invoke("crearUsuario", new object[] {
                        nombres,
                        apellidos,
                        contraseña,
                        apodo,
                        llave});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void crearUsuarioAsync(string nombres, string apellidos, string contraseña, string apodo, string llave) {
            this.crearUsuarioAsync(nombres, apellidos, contraseña, apodo, llave, null);
        }
        
        /// <remarks/>
        public void crearUsuarioAsync(string nombres, string apellidos, string contraseña, string apodo, string llave, object userState) {
            if ((this.crearUsuarioOperationCompleted == null)) {
                this.crearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("crearUsuario", new object[] {
                        nombres,
                        apellidos,
                        contraseña,
                        apodo,
                        llave}, this.crearUsuarioOperationCompleted, userState);
        }
        
        private void OncrearUsuarioOperationCompleted(object arg) {
            if ((this.crearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearUsuarioCompleted(this, new crearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int agregarConocimiento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombreConocimiento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int dominio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string formaAprendido, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string comentario) {
            object[] results = this.Invoke("agregarConocimiento", new object[] {
                        nombreConocimiento,
                        apodo,
                        dominio,
                        formaAprendido,
                        comentario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void agregarConocimientoAsync(string nombreConocimiento, string apodo, int dominio, string formaAprendido, string comentario) {
            this.agregarConocimientoAsync(nombreConocimiento, apodo, dominio, formaAprendido, comentario, null);
        }
        
        /// <remarks/>
        public void agregarConocimientoAsync(string nombreConocimiento, string apodo, int dominio, string formaAprendido, string comentario, object userState) {
            if ((this.agregarConocimientoOperationCompleted == null)) {
                this.agregarConocimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarConocimientoOperationCompleted);
            }
            this.InvokeAsync("agregarConocimiento", new object[] {
                        nombreConocimiento,
                        apodo,
                        dominio,
                        formaAprendido,
                        comentario}, this.agregarConocimientoOperationCompleted, userState);
        }
        
        private void OnagregarConocimientoOperationCompleted(object arg) {
            if ((this.agregarConocimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarConocimientoCompleted(this, new agregarConocimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] getConocimientosDeUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo) {
            object[] results = this.Invoke("getConocimientosDeUsuario", new object[] {
                        apodo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getConocimientosDeUsuarioAsync(string apodo) {
            this.getConocimientosDeUsuarioAsync(apodo, null);
        }
        
        /// <remarks/>
        public void getConocimientosDeUsuarioAsync(string apodo, object userState) {
            if ((this.getConocimientosDeUsuarioOperationCompleted == null)) {
                this.getConocimientosDeUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConocimientosDeUsuarioOperationCompleted);
            }
            this.InvokeAsync("getConocimientosDeUsuario", new object[] {
                        apodo}, this.getConocimientosDeUsuarioOperationCompleted, userState);
        }
        
        private void OngetConocimientosDeUsuarioOperationCompleted(object arg) {
            if ((this.getConocimientosDeUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConocimientosDeUsuarioCompleted(this, new getConocimientosDeUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] getContactos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo) {
            object[] results = this.Invoke("getContactos", new object[] {
                        apodo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getContactosAsync(string apodo) {
            this.getContactosAsync(apodo, null);
        }
        
        /// <remarks/>
        public void getContactosAsync(string apodo, object userState) {
            if ((this.getContactosOperationCompleted == null)) {
                this.getContactosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContactosOperationCompleted);
            }
            this.InvokeAsync("getContactos", new object[] {
                        apodo}, this.getContactosOperationCompleted, userState);
        }
        
        private void OngetContactosOperationCompleted(object arg) {
            if ((this.getContactosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContactosCompleted(this, new getContactosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool iniciarSesion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Apodo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string codigo) {
            object[] results = this.Invoke("iniciarSesion", new object[] {
                        Apodo,
                        pass,
                        codigo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void iniciarSesionAsync(string Apodo, string pass, string codigo) {
            this.iniciarSesionAsync(Apodo, pass, codigo, null);
        }
        
        /// <remarks/>
        public void iniciarSesionAsync(string Apodo, string pass, string codigo, object userState) {
            if ((this.iniciarSesionOperationCompleted == null)) {
                this.iniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OniniciarSesionOperationCompleted);
            }
            this.InvokeAsync("iniciarSesion", new object[] {
                        Apodo,
                        pass,
                        codigo}, this.iniciarSesionOperationCompleted, userState);
        }
        
        private void OniniciarSesionOperationCompleted(object arg) {
            if ((this.iniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.iniciarSesionCompleted(this, new iniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double getKarmaTotal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo) {
            object[] results = this.Invoke("getKarmaTotal", new object[] {
                        apodo});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getKarmaTotalAsync(string apodo) {
            this.getKarmaTotalAsync(apodo, null);
        }
        
        /// <remarks/>
        public void getKarmaTotalAsync(string apodo, object userState) {
            if ((this.getKarmaTotalOperationCompleted == null)) {
                this.getKarmaTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKarmaTotalOperationCompleted);
            }
            this.InvokeAsync("getKarmaTotal", new object[] {
                        apodo}, this.getKarmaTotalOperationCompleted, userState);
        }
        
        private void OngetKarmaTotalOperationCompleted(object arg) {
            if ((this.getKarmaTotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKarmaTotalCompleted(this, new getKarmaTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool insertNumSession([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int numSession) {
            object[] results = this.Invoke("insertNumSession", new object[] {
                        apodo,
                        numSession});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertNumSessionAsync(string apodo, int numSession) {
            this.insertNumSessionAsync(apodo, numSession, null);
        }
        
        /// <remarks/>
        public void insertNumSessionAsync(string apodo, int numSession, object userState) {
            if ((this.insertNumSessionOperationCompleted == null)) {
                this.insertNumSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertNumSessionOperationCompleted);
            }
            this.InvokeAsync("insertNumSession", new object[] {
                        apodo,
                        numSession}, this.insertNumSessionOperationCompleted, userState);
        }
        
        private void OninsertNumSessionOperationCompleted(object arg) {
            if ((this.insertNumSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertNumSessionCompleted(this, new insertNumSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hello([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string name) {
            object[] results = this.Invoke("hello", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void helloAsync(string name) {
            this.helloAsync(name, null);
        }
        
        /// <remarks/>
        public void helloAsync(string name, object userState) {
            if ((this.helloOperationCompleted == null)) {
                this.helloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloOperationCompleted);
            }
            this.InvokeAsync("hello", new object[] {
                        name}, this.helloOperationCompleted, userState);
        }
        
        private void OnhelloOperationCompleted(object arg) {
            if ((this.helloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.helloCompleted(this, new helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] getConocimientos() {
            object[] results = this.Invoke("getConocimientos", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getConocimientosAsync() {
            this.getConocimientosAsync(null);
        }
        
        /// <remarks/>
        public void getConocimientosAsync(object userState) {
            if ((this.getConocimientosOperationCompleted == null)) {
                this.getConocimientosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConocimientosOperationCompleted);
            }
            this.InvokeAsync("getConocimientos", new object[0], this.getConocimientosOperationCompleted, userState);
        }
        
        private void OngetConocimientosOperationCompleted(object arg) {
            if ((this.getConocimientosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConocimientosCompleted(this, new getConocimientosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getNumSession([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo) {
            object[] results = this.Invoke("getNumSession", new object[] {
                        apodo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getNumSessionAsync(string apodo) {
            this.getNumSessionAsync(apodo, null);
        }
        
        /// <remarks/>
        public void getNumSessionAsync(string apodo, object userState) {
            if ((this.getNumSessionOperationCompleted == null)) {
                this.getNumSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNumSessionOperationCompleted);
            }
            this.InvokeAsync("getNumSession", new object[] {
                        apodo}, this.getNumSessionOperationCompleted, userState);
        }
        
        private void OngetNumSessionOperationCompleted(object arg) {
            if ((this.getNumSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNumSessionCompleted(this, new getNumSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WS/", ResponseNamespace="http://WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int getTipoUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apodo) {
            object[] results = this.Invoke("getTipoUsuario", new object[] {
                        apodo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getTipoUsuarioAsync(string apodo) {
            this.getTipoUsuarioAsync(apodo, null);
        }
        
        /// <remarks/>
        public void getTipoUsuarioAsync(string apodo, object userState) {
            if ((this.getTipoUsuarioOperationCompleted == null)) {
                this.getTipoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTipoUsuarioOperationCompleted);
            }
            this.InvokeAsync("getTipoUsuario", new object[] {
                        apodo}, this.getTipoUsuarioOperationCompleted, userState);
        }
        
        private void OngetTipoUsuarioOperationCompleted(object arg) {
            if ((this.getTipoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTipoUsuarioCompleted(this, new getTipoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void crearUsuarioCompletedEventHandler(object sender, crearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void agregarConocimientoCompletedEventHandler(object sender, agregarConocimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarConocimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarConocimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getConocimientosDeUsuarioCompletedEventHandler(object sender, getConocimientosDeUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConocimientosDeUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConocimientosDeUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getContactosCompletedEventHandler(object sender, getContactosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContactosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContactosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void iniciarSesionCompletedEventHandler(object sender, iniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class iniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal iniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getKarmaTotalCompletedEventHandler(object sender, getKarmaTotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKarmaTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKarmaTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void insertNumSessionCompletedEventHandler(object sender, insertNumSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertNumSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertNumSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void helloCompletedEventHandler(object sender, helloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getConocimientosCompletedEventHandler(object sender, getConocimientosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConocimientosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConocimientosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getNumSessionCompletedEventHandler(object sender, getNumSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNumSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNumSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getTipoUsuarioCompletedEventHandler(object sender, getTipoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTipoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTipoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591